name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  JWT_SECRET: fakeJwtToken
  PORT: 3000
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Print Jwt Secret
        run: echo "$JWT_SECRET"
      - name: Print Port
        run: echo "${{env.PORT}}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "..."
